const fs = require('fs');

const names = 
    [
    "Pratyas Kumar",
    "Milind Vedi",
    "Gautam Pawar",
    "Pirjada Mohammedtanvir Jamilahemad",
    "Ajay Kumar Verma",
    "Shaikh Vakas Ahmed Humaiyun",
    "ANTONY AJAY GEOFFREY",
    "Ankit Kumar",
    "Arnab Bera",
    "Ankit Kumar",
    "Durga Prasad Behera",
    "Tanzeem Ahmed",
    "Raushan Roy",
    "Pradeep Maurya",
    "MAHADEVA SWAMY GN",
    "Brijesh Kumar Yadav",
    "Sagar Kumar",
    "Afzal Ahmad",
    "Mohit Verma",
    "Nikhilesh Kumar Mishra",
    "Sankalp Trimade",
    "Arunkumar Ajaykumar Menon",
    "Ankit Dagar",
    "M Gopal Krishna",
    "Raj Kumar Vishwakarma",
    "Himanshu Joshi",
    "Priyanshu Choudhary",
    "Arpit Jain",
    "Faisal Ali",
    "Abhishek Chauhan",
    "Saurabh Raj",
    "Abhishek Yadav",
    "Wajhul Huda",
    "Reena Kahar",
    "Abhishek Sahani",
    "Bura Vaishnavi",
    "Sandeep R Kurup",
    "Abhishek Sahani",
    "Pirjada Mohammedtanvir",
    "Yarramsetti Jaya Kiran Kumar",
    "Donel Sinha",
    "Singam Saiprasad",
    "Rushikesh Ramdas Tupkar",
    "Pratyendu Sarkar",
    "Abhishek Ojha",
    "Chandan Kumar",
    "Renuka Choudhary",
    "Chhaya Chouhan",
    "Manav",
    "Tejasvi Chauhan",
    "Sagar Kumar",
    "Divya Hirve",
    "Anshul Nair",
    "Mohammad Shahrukh",
    "Satyam Jaiswal",
    "Sowndarya.S",
    "Vivek Kumar Patel",
    "Ajinkya Rajendra Padule",
    "Peeyush Mohapatra",
    "Sushant Rawat",
    "Durgesh Santosh Sonawale",
    "Subramanyam Reddy",
    "Parish Jain",
    "MADHUR PATARI",
    "Devathoti Venkataramana",
    "Mayank Joshi",
    "Govinda Kumar Mishra",
    "Ankit Kumar",
    "Omkar Pradeep Pawar",
    "Arbaz Shah",
    "Sonu Kumar",
    "Tanisht Gupta",
    "Nikita Kiran Parate",
    "Keval Parekh",
    "GOLLA SREENATH",
    "Supriya Ghorai",
    "Nithin T Abraham",
    "Ravi Lohar"
  ]
  
const profileImages = [
    "WhatsApp Image 2023-07-04 at 8.43.43 PM.jpeg",
    "WhatsApp Image 2023-06-08 at 6.50.41 PM.jpeg",
    "WhatsApp Image 2023-07-05 at 11.40.27 AM.jpeg",
    "WhatsApp Image 2023-01-12 at 11.12.00 PM - Tanvir Pirjada.jpeg",
    "1659464779245.jpg",
    "WhatsApp Image 2023-07-05 at 11.41.06 AM.jpeg",
    "picture - Ajay Geoffrey.jpg",
    "image - Ankit Kumar.jpg",
    "Arnabpic1 - Arnab Bera.jpg",
    "pic - ankit kumar.jpg",
    "WhatsApp Image 2021-12-20 at 6.11.55 PM - Durga Prasad Behera.jpeg",
    "IMG-20220207-WA0044 - Tanzeem Ahmed.jpg",
    "1643906266811 - Raushan Roy.jpeg",
    "IMG-20230119-WA0000 - pradeep maurya.jpg",
    "p_Mahadevaswamygn - mahadeva swamy GN.jpg",
    "brijesh - Brijesh yadav.jpg",
    "20211119_154057 - sagar kumar.jpg",
    "DSC_0098 - afzal malik.JPG",
    "my photo1 - Mohit Verma.jpg",
    "IMG_20210902_170322 - Nikilesh mishra.jpg",
    "sankalp pic - Sankalp Trimade.jpg",
    "1674051863481 - Arun Menon.jpg",
    "Screenshot_2022-10-03-15-30-00-46_99c04817c0de5652397fc8b56c3b3817 - Ankit Dagar.jpg",
    "DSC_0849 (1) - M Gopal Krishna.JPG",
    "photo - Raj Kumar Vishwakarma.jpg",
    "him - HIMANSHU JOSHI.jpg",
    "IMG_20220307_233202 (2) - priyanshu choudhary.jpg",
    "20230120_103544 - Arpit Jain 4454.jpg",
    "IMG_20230120_183038 - Faisal Ali.jpg",
    "Screenshot_20230119_063856 - Abhishek Chauhan.png",
    "saurabh - Saurabh Raj pandey.jpg",
    "WIN_20220402_15_42_14_Pro - Abhishek Yadav.jpg",
    "IMG20211024104717 - Wajhul Huda.jpg",
    "m_E - Reena Kahar.jpeg",
    "IMG_20200703_203441 - Abhishek Sahani.jpg",
    "IMG_20221003_113226 - Vaishnavi Bura.jpg",
    "IMG_20221222_141150-01 - SANDEEP R KURUP.jpeg",
    "IMG_20200703_203441 - Abhishek Sahani.jpg",
    "WhatsApp Image 2023-01-12 at 11.12.00 PM - Tanvir Pirjada.jpeg",
    "PicsArt_03-08-04.46.35 - jaya kiran kumar Yerramsetti.jpg",
    "WhatsApp Image 2023-07-03 at 6.08.27 PM.jpeg",
    "WhatsApp Image 2023-06-24 at 1.49.14 PM.jpeg",
    "Passport - Rushikesh Tupkar.jpg",
    "self1 - Pratyendu Sarkar.jpg",
    "WhatsApp Image 2023-07-17 at 19.39.50.jpeg",
    "IMG_20230219_115815 - Chandan Kumar.jpg",
    "selfphoto - renuka chaudhary.jpeg",
    "WhatsApp Image 2023-08-28 at 15.37.19.jpeg",
    "WhatsApp Image 2023-08-28 at 16.45.29.jpeg",
    "PicsArt_02-15-09.43.37 - T E J A S V I.jpg",
    "20211119_154057 - sagar kumar.jpg",
    "photo - Divya Hirve.jpg",
    "IMG_20230131_150134 - Anshul Nair.jpg",
    "IMG_20220516_172945_copy_500x500 - royal Saifi.jpg",
    "photo_2023-07-19_14-32-57 - Satyam Jaiswal.jpg",
    "IMG_20230112_183327 - Sowndarya S.jpg",
    "vivekPassportPhoto - Vivek Patel.jpg",
    "profile - Ajinkya Padule.jpg",
    "passport photo-2 - peeyush mohapatra.jpg",
    "ProfilePic.jpg - sushant rawat.jpeg",
    "IMG_20190318_203306 - Durgesh Sonawale.jpg",
    "SubramanyamReddy - reddy subramanyam7788.jpg",
    "pj (1) - Parish Jain.png",
    "2021_02_22_1172520992111275821 - Madhur.jpg",
    "photo - Venkataramana Devathoti.jpg",
    "mayank photo - Mayank Joshi.jpeg",
    "Govinda photo - govinda mishra.jpeg",
    "IMG_20230929_175120 - Ankit Kumar.jpg",
    "IDPHOTO - Omkar PAWAR.jpg",
    "052ef42d-a49b-41ff-9b50-024ea06f44b8 - Arbaz Shah.png",
    "skv - Sonu Kumar.jpg",
    "Profile - Tanisht Gupta.png",
    "WhatsApp Image 2023-08-21 at 10.21.12 PM - Nikita Parate.jpeg",
    "Keval_PassportSize - Keval Parekh.jpg",
    "sreenath_picture - SREENATH GOLLA.png",
    "Photograph - SUPRIYA GHORAI.png",
    "photo - Nithin Abraham.png",
    "Photo - Ravi Lohar.jpg"
  ] 

const companyLogos = [
  "mountblue_ventures",
  "mountblue_ventures",
  "mountblue_ventures",
  "mountblue_ventures",
  "cavista",
  "techpanion",
  "pratishthan_venture",
  "mountblue_ventures",
  "mountblue_ventures",
  "mountblue_ventures",
  "mountblue_ventures",
  "mountblue_ventures",
  "mountblue_ventures",
  "mountblue_ventures",
  "mountblue_ventures",
  "Enterprise_Bot",
  "mojito_labs",
  "tsys",
  "shriram_technologies",
  "tsys",
  "tezo",
  "mountblue_ventures",
  "mountblue_ventures",
  "mountblue_ventures",
  "webmd",
  "orane",
  "geekster",
  "reward360",
  "reward360",
  "reward360",
  "reward360",
  "reward360",
  "reward360",
  "athmin",
  "mountblue_ventures",
  "spandana",
  "haspaces",
  "rchill",
  "rchill",
  "rchill",
  "analytic_edge",
  "analytic_edge",
  "accion_Labs",
  "gulbrandsen",
  "webmd",
  "guru_ji_astro",
  "1_K",
  "guru_ji_astro",
  "guru_ji_astro",
  "coedify",
  "bitxia_tech",
  "cbsl",
  "unravel",
  "decimal_technology",
  "inspiron_labs",
  "progress",
  "inspiron_labs",
  "innostax",
  "mtechzila",
  "innostax",
  "go_Digital",
  "fitpage",
  "trak_n_tell",
  "trak_n_tell",
  "entropik_tech",
  "entropik_tech",
  "idea_forge",
  "eupheus",
  "I2V",
  "flurn",
  "dehaat",
  "webmd",
  "avrl",
  "technous",
  "indus",
  "flurn",
  "bytestrone_india_private_limited",
  "testhouse"
]
 
const titles = [
  "ECE Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Civil Engineer to Software Developer Engineer",
  "Electrical Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Civil Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Bio. Tech Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Electrical Engineer to Software Developer Engineer",
  "Bio. Tech Engineer to Software Developer Engineer",
  "Civil Engineer to Software Developer Engineer",
  "Civil Engineer to Software Developer Engineer",
  "ECE Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer", 
  "Successfully Placed as a Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "ECE Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Instrumentation Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Civil Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "Civil Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "ECE Engineer to Software Developer Engineer",
  "Civil Engineer to Software Developer Engineer",
  "Civil Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "Civil Engineer to Software Developer Engineer",
  "ECE Engineer to Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "Electrical Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "ECE Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "ECE Engineer to Software Developer Engineer",
  "Instrumentation Engineering Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Civil Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "Electrical Engineer to Software Developer Engineer",
  "Mathematics Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "ECE Engineer to Software Developer Engineer",
  "ECE Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "ECE Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Civil Engineer to Software Developer Engineer",
  "Civil Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
  "Electrical Engineer to Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "Mechanical Engineer to Software Developer Engineer",
  "Successfully Placed as a Software Developer Engineer",
];

const data = [];
 
for (let i = 0; i < names.length; i++) {
  const jsonEntry = {
    name: names[i],
    profileImage: profileImages[i],
    companyLogo: companyLogos[i],
    title: titles[i]
  };
  data.push(jsonEntry);
}
const jsonData = JSON.stringify(data, null, 2);
fs.writeFileSync('data.json', jsonData);

console.log('Data has been saved to data.json');