const fs = require('fs');

const names = [
  "Yash Chandra Verma",
  "Pushpinder Singh",
  "Krishna Kavali",
  "Ragini Raj",
  "Vaibhav Kachare",
  "Sonam",
  "Gyanaranjan panda",
  "Honnaraju R",
  "Ashish Kumar Aman",
  "Sourav Dey",
  "Vishwanath Vasant Telang",
  "Amit Kumar",
  "Vinod Reddy",
  "Vamsi Krishna",
  "Rahul Kumar",
  "Kartikeyan Palani",
  "Pritam Banerjee",
  "Sanskar Gupta",
  "Faisal Ashraf Wani",
  "Gaurav Kumar",
  "Ravi reddy",
  "Karan Kishore Bairagi",
  "Lava Kumar Nandam",
  "Dhananjayan D",
  "Swami Sonam Singh",
  "Manish Chauhan",
  "Sudhanshu Kumar",
  "G Gowrishankar",
  "Ashwini Kumar",
  "Rohan Kumar Singh",
  "Amit Mandal",
  "Mohammad Bilal Khalid",
  "Rahul Sureka",
  "Chetan Tanwar",
  "Gopinath",
  "Mohit Singh Tomar",
  "Rohit Kumar",
  "Ravi Panchal",
  "Pushpak Mahajan",
  "Ankit Jha",
  "Yash Acholkar",
  "Sridhar NS",
  "Nagaraj G",
  "Dnyaneshwar Ghodse",
  "Abhinav Sharma",
  "Bhavesh Gupta",
  "Rishab Rajput",
  "Sanjeev Sagar",
  "Mohd Shahid Adoni",
  "Sourav Ghosh",
  "Anurag Ojha",
  "Sakshi Subhash Gaye",
  "Shashank Kumar Dubey",
  "Jalal Uddin SK",
  "Manish Borse",
  "Vishwesh Savadatti",
  "Pranshu Jain",
  "Prakhar Agarwal",
  "Wajhul Huda",
  "Sameep Gowda",
  "Prabhakar Ranjan",
  "Shiv Singh",
  "Ajaya Kumar Das",
  "Shubham Jain",
  "Harish Kumar",
  "Saurajit Das",
  "Utkarsh Singh",
  "Rahul Rokhale",
  "Prasang Chouksey",
  "Rahul Dev",
  "Amanpreet Singh",
  "Kumar Piyush",
  "Neeraj Kumar",
  "Gajendra Malviya",
  "Dinesh Yadav",
  "Shivam Pandey",
  "Pranav AS",
  "Shubhankit Tiwari",
  "Rushikesh Laxman Potadar",
  "Abhishek Kumar",
  "Vemuluri Krupasankar",
  "Utkarsh Gangwar",
  "Riya Mishra",
  "Afzal Hussain",
  "Ashish Adarsh",
  "Prasanta Kumar Seemala",
  "Ashwin Kumar R",
  "Sahil Debnath",
  "Rohith Kumar S",
  "Ayushi Agarwal",
  "Sanjay Kumar Singh",
  "Nauman Ansari",
  "Hanamantappa Nagaral",
  "Rashmi Saini",
  "Sagar Krishnat Chopdar",
  "Vishal Yadav",
  "Yogesh Solanki",
  "Venu Narayanrao Kulkarni",
  "Arbaz Ali",
  "Vikash Kumar",
  "Akash Mishra",
  "Ayaaz Mazhar",
  "Kartik Gupta",
  "Kaushal Sorathiya",
  "Buvanesh Kumar",
  "Saurabh Garg",
  "Sai Pranav Tunuguntla",
  "Vinay Kumar",
  "Dipali Pandhari Bari",
  "Sadanand Fulari",
  "Sai Kiran",
  "Karri Devi",
  "Anmol Agarwal",
  "Asutosh Jena",
  "Shaik Mahaboob Jani",
  "Sanjay Kushwaha",
  "Joseph K Anoj",
  "Hrishikesh Kulkarni",
  "Shashikant Annarao Sahane",
  "Neha Bhat",
  "SKM Vali",
  "Ankit Patil",
  "Neelkanth S",
  "Kiran Chaudhari",
  "Akshita Sagar",
  "Pawan Kumar",
  "Amit Kumar",
  "Nipun Sinha",
  "Ashish Kumar Sharma",
  "Srishti Pal",
  "Shreyash Waghmare",
  "Rabish Kumar",
  "Vivek Kumar",
  "Naveen Katiyar",
  "Yogesh Rathod",
  "Susmisri",
  "Nagaraj",
  "Vasu Dev Mandal",
  "Gunji Venkatesh",
  "Dhananjaya Dash",
  "Roshan Kumar Sharma",
  "Suresha B M",
  "Abhijeet",
  "Mukul Paul",
  "Sai Vardhan Reddy",
  "Mayank Choudhary",
  "Chandani Navadiya",
  "Sachin Pundir",
  "Dheeraj Sharma",
  "Mukul Gupta",
  "Maitrish Mukherjee",
  "Mohd Sami",
  "Jeevan Kalyan Reddy",
  "Suryansh Soni",
  "Prathamesh Jadhav",
  "Akanksha Sanjayrao Vibhute",
  "Akash Vitthal Patil",
  "Shashank Suryavanshi",
  "Pranathi Kairam Konda",
  "Ajay Jadhao",
  "Aman Pal",
  "Rakesh Sonkar",
  "Minu Kumari",
  "Arpit Joshi",
  "Lav Palve",
  "Yash Jadoun",
  "Dipankar Maurya",
  "Debashish Mahana",
  "Rahul Dev",
  "Ajay Santosh Bharsakale",
  "Arshek Singh",
  "Rahul Sharma",
  "Jayraj Rajendrasing Pawar",
  "Vijayant Prateek",
  "Nipun Sharma",
  "Ansu Kumar",
  "Manav Shah",
  "Vikas Mishra",
  "Siddiq Pasha S K",
  "Abhishek Ajay Diwete",
  "Sagar Manna",
  "Ujjwal Arvind Lade",
  "Ajay Kumar Verma",
  "Virender Kumar",
  "Anil Kumar Reddy",
  "Prathamesh Baban Harad",
  "Zeeshan Ansari",
  "Hrishi Kumawat",
  "Akash Ashok Thopate",
  "Shaik Mohammed Siraj Ahmed",
  "Chetan Shivhare",
  "Salim Ilahi Lain",
  "Chinee Santosh Ramu",
  "Drishti Dua",
  "Gaurav Yadav",
  "Dhananjay Kumar",
  "Nitin Mankar",
  "Kushagra Gupta",
  "Shubham Chandrakant Shukla",
  "Mohit Kumar",
  "Nandini Vijayvargiya",
  "Vishal Hanmantrao Sonkamble",
  "Anket Pratap Singh",
  "Vikash Kumar Sangwan",
  "Abhishek Joshi",
  "Chandradeep Prasad",
  "Sushant Kumar",
  "Vishnu Pumar",
  "Shubham Mohan",
  "Sumit Raj",
  "Bipin Maurya",
  "Umang Nagar",
  "Ujjawal Joshi",
  "Mohd Shah Mukit Alam",
  "Sourabh Mittal",
  "Ayesha Tabassum",
  "Nagsen Shinde",
  "Ankit Pal",
  "SK Sharuk Mehetab",
  "Mohd Saqib",
  "Sumit Mishra",
  "Lavinsh Rathor",
  "Arman Ali",
  "Gulshan Kumar",
  "Rahul Bangari",
  "Mohd Aqib",
  "Vishal Patidar",
  "Aman Upadhyay",
  "Kundala Anil Kumar",
  "Ashok Yelagandula",
  "Abhishek Kushwaha",
  "Jaimeen Vinjamury",
  "Toufik Desai",
  "Iswarabhottla Vamsi",
  "Saijal Chandani",
  "Quazi Yadgar Husain",
  "Anujkumar Tiwari",
  "Mohammad Faiz Khan"
];  
  


const companyLogos = [
  "Fynd",
  "AshmarIPF",
  "London_Consulting_Group",
  "Technack",
  "TeamLease",
  "Citius_Tech",
  "Capgemini",
  "ThatMate",
  "Net_Ambit",
  "Infosys",
  "Capgemini",
  "Genpact",
  "Avizva_Solutions",
  "Avizva_Solutions",
  "Avizva_Solutions",
  "Ramco_Systems",
  "Molecular_Connections",
  "Brillio",
  "Radiansys",
  "Knoldus_Software",
  "Infosys",
  "Analytic_Edge",
  "Avizva_Solutions",
  "Avizva_Solutions",
  "Avizva_Solutions",
  "Avizva_Solutions",
  "Avizva_Solutions",
  "Avizva_Solutions",
  "IVY_Comptech",
  "IVY_Comptech",
  "IVY_Comptech",
  "Isthara",
  "Genpact",
  "Soc_Gen",
  "Soc_Gen",
  "Genpact",
  "NetCore_Cloud",
  "Lucent_Innovation",
  "Amdocs",
  "IVY_Comptech",
  "Infosys",
  "Wiley_Nm_Three",
  "Karomi",
  "Dhwani_RIS",
  "Isthara",
  "Shiprocket",
  "Skillgigs",
  "Skillgigs",
  "Rapyder",
  "Infosys",
  "Skillgigs",
  "TCS",
  "SarvaGram",
  "SarvaGram",
  "SarvaGram",
  "Optum",
  "PayPal",
  "PayPal",
  "Genpact",
  "Genpact",
  "Genpact",
  "Genpact",
  "Genpact",
  "Avizva",
  "Shiprocket",
  "Thermax_Babcock_&_Wilcox_Energy_Solutions_Pvt_Ltd",
  "Bluewud",
  "Genpact",
  "Genpact",
  "ScaleX",
  "Paypal",
  "Paypal",
  "Genpact",
  "Avizva_Solutions",
  "Reqip",
  "TCS",
  "IVY_Comptech",
  "IVY_Comptech",
  "IVY_Comptech",
  "IVY_Comptech",
  "IVY_Comptech",
  "IVY_Comptech",
  "IVY_Comptech",
  "IVY_Comptech",
  "SenRa",
  "Tier5_Technology_Solutions_Private_Limited",
  "IVY_Comptech",
  "Value_Soft",
  "SAPIENS",
  "Genpact",
  "Genpact",
  "Genpact",
  "Genpact",
  "Genpact",
  "Genpact",
  "Genpact",
  "Genpact",
  "Genpact",
  "Genpact",
  "Genpact",
  "Genpact",
  "Genpact",
  "Zolostays",
  "Quinta",
  "Vertocity",
  "Publicis_Sapient",
  "Smart_Docs",
  "IVY_Comptech",
  "IVY_Comptech",
  "Bristlecone",
  "Soc_Gen",
  "Genpact",
  "Thoughts2Binary",
  "Genpact",
  "Publicis_Sapient",
  "SenRa",
  "Publicis_Sapient",
  "Infosys",
  "Wipro",
  "Genpact",
  "Go_Group",
  "Accion_Labs",
  "Oracle",
  "Divine",
  "Publicis_Sapient",
  "Radiansys",
  "Soc_Gen",
  "Soc_Gen",
  "Radiansys",
  "ismart.asia_Technology",
  "Rakuten",
  "Radiansys",
  "Genpact",
  "Rakuten",
  "Publicis_Sapient",
  "IVY_Comptech",
  "Hexaware",
  "SmartTek21",
  "Tech_Mahindra",
  "Capgemini",
  "De_Pronto",
  "Cognitive_Clouds",
  "Publicis_Sapient",
  "Publicis_Sapient",
  "TCS",
  "Quinnox",
  "Crimson_AI",
  "De_Pronto ",
  "Colexion",
  "De_Pronto",
  "FWC_IT_Services",
  "Dodoskills",
  "Infosys",
  "Radiansys",
  "Radiansys",
  "Capgemini",
  "ParallelCap",
  "IBM",
  "Tarento",
  "AVIZVA",
  "People_Tech",
  "Krati_Consultancy",
  "Telstra",
  "Dhwani_RIS",
  "OnGraph",
  "Altimetrik",
  "Indigene",
  "Zolostays",
  "IDFC",
  "Clarivate",
  "Parallel_Cap",
  "Acnovate",
  "HashStudioz",
  "KPMG",
  "Primotech",
  "Cavista",
  "Cavista",
  "Analytic_Edge",
  "Solera",
  "IMocha",
  "IVY_Comptech",
  "IVY_Comptech",
  "OnGraph",
  "Nolimit_City",
  "Cognizant",
  "Solera",
  "Piexxi",
  "Cyntexa",
  "Solera",
  "WeRize",
  "IMocha",
  "Chaincode_Consulting",
  "Solera",
  "Full_Creative",
  "Agile_Cockpit",
  "Solera",
  "Solera",
  "Airtel",
  "Solera",
  "Solera",
  "Thermofisher",
  "Servosys",
  "Comviva",
  "Detect_Technologies",
  "Workllama",
  "Nissan_Digital",
  "Nissan_Digital",
  "Finway",
  "Data_Foundary",
  "Comviva",
  "Comviva",
  "Comviva",
  "RestoLabs",
  "Nissan_Digital",
  "Nissan_Digital",
  "Cloudsmartz",
  "Cloudsmartz",
  "Cloudsmartz",
  "IVY",
  "IVY",
  "Uniacco",
  "Geekster",
  "AVRL",
  "Geekster",
  "Geekster",
  "Recur_club",
  "Bijak",
  "Recur_club",
  "IVY_Tech",
  "Mountblue_Ventures",
  "Mountblue_Ventures",
  "KPMG_Global_Services_Private_Limited",
  "Wingify",
  "ADP_Pvt_ltd",
  "Flutura",
  "Analytic_edge",
  "Prosperix",
  "Mountblue_Ventures"
]

 
const titles = ["Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Big Data Analytics Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"BCA Engineer to Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Information Science and Engineering Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Digital Communications Engineer to Software Developer Engineer"
,"Petroleum Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Petroleum Engineer to Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Science Engineer to Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Electronics and Instrumentation Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Engineer to Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"AEIE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
" Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Computer Applications Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Computer Applications Engineer to Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Computer Applications Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Electrical Engineer to Software Developer Engineer",
" Engineer to Software Developer Engineer",
" Engineer to Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Computer Applications Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
" Engineer to Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Computer Applications Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Computer Applications Engineer to Software Developer Engineer",
" Engineer to Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Petroleum Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Computer Applications Engineer to Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Computer Applications Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Computer Applications Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Petroleum Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"E&C Engineer to Software Developer Engineer",
"Production Engineering Engineer to Software Developer Engineer",
"Computer Applications Engineer to Software Developer Engineer",
"E&C Engineer to Software Developer Engineer",
"Electrical Engineer to Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Information Science Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Electrical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Computer Applications Engineer to Software Developer Engineer",
"Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Chemical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Civil Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Aerospace Engineer to Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Electrical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Civil Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Electrical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Others Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"E&E Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Electronics & Communications Engineer to Software Developer Engineer",
"Other Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"ECE Engineer to Software Developer Engineer",
"Mechanical Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Computer Application Engineer to Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer",
"Successfully Placed as a Software Developer Engineer"]


const data = [];
 
for (let i = 0; i < names.length; i++) {
  const jsonEntry = {
    name: names[i],
    profileImage: "prfile.png",
    companyLogo: companyLogos[i],
    title: titles[i]
  };
  data.push(jsonEntry);
}
const jsonData = JSON.stringify(data, null, 2);
fs.writeFileSync('data1.json', jsonData);

console.log('Data has been saved to data.json');